#!/bin/sh
set -ue -o pipefail
export LC_ALL=C

main() {
    randomstr=$(date +%s | sha256sum | base64 | head -c 32 ; echo)
    tmpphp=${randomstr}.php

    cat <<-"EOS" >${tmpphp}
<?php
$dir = substr(dirname($_SERVER['PHP_SELF']),strlen($_SERVER['DOCUMENT_ROOT']));
echo "<h2>Index of ".$dir.":</h2>";
$g = glob("*");
usort($g,function($a,$b) {
    if(is_dir($a) == is_dir($b))
        return strnatcasecmp($a,$b);
    else
        return is_dir($a) ? -1 : 1;
});
echo implode("<br>",array_map(function($a) {return '<a href="'.$a.'">'.$a.'</a>';},$g));
EOS
    trap 'rm -v ${tmpphp}' 1 2 3 15
    url="http://localhost:9999/${tmpphp}"
    open $url
    php -S localhost:9999

}
main "$@"
